config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy]
  end
  
  resources :posts, only: [:new, :create, :destroy, :edit, :update] do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]

  namespace :api, defaults: { format: :json } do
    resources :posts, only: [:index] do
      resources :comments, only: [:create, :index]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include Devise::JWT::RevocationStrategies::JTIMatcher

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :jwt_authenticatable, jwt_revocation_strategy: self

  has_many :posts, foreign_key: :author_id, class_name: 'Post'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    Post.includes(:user).where(author_id: id).last(3)
  end

  # User::Roles
  # The available roles
  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:id)
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.includes(:user).where(author_id: @user.id)
  end

  def create
    @user = User.new(user_params)
    return unless @user.save

    flash[:success] = 'Signed in successfully'
    redirect_to user_post_path(@post.author_id, @post.id)
    redirect_to @user
  end

  def edit
    current_user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :photo, :posts_counter, :email, :password)
  end

  def display_error_message
    flash.now[:danger] = 'Form contains errors. Please see fields marked in red'
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def image_url(user)
    user.photo || "https://ui-avatars.com/api/?name=#{user.name}&background=random"
  end

  def post_counter(user)
    user.posts_counter || 0
  end

  def posts?(posts)
    posts.empty? ? 'You have no posts yet, Try to add a post 😊' : "#{@user.name}\'s recents posts"
  end
end

app/views/users/index.html.erb
<div class="container min-vh-100 d-flex flex-column align-content-center justify-content-start">
  <h1 class="py-5">Welcome to your Blog App</h1>
  <div class="wrapper d-flex align-content-center justify-content-center flex-wrap my-5">
    <% @users.each do |user| %>
        <%=  link_to user_path(user.id), {class: "user_container d-flex flex-column text-center text-decoration-none mx-auto"} do%>
          <div class="image-container rounded-circle">
            <%=image_tag(image_url(user), alt: "User#{user.id} photo", class: "rounded-circle w-100") %>
          </div>
          <h2><%= user.name %></h2>
          <span>Number of posts: <%= post_counter(user) %></span>
        <%end%>
    <%end%>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= render partial: "_partials/header", locals: {user: @user} %>
  <div class="w-100 border border-dark my-4 p-3">
     <h2>BIO</h2>
     <p><%= @user.bio %></p>
  </div>
  <h2 class="text-decoration-underline text-monospace"><%= posts?(@posts) %></h2>
  <% @user.most_recent_posts.each do |post| %>
    <%= render partial: "posts/post", locals: {post: post, user: @user} %>
  <% end %>
  <div class="d-flex justify-content-center align-items-center w-100 py-5">
    <%= link_to "See all posts", user_posts_path(@user.id), {class: "btn btn-primary w-25 m-3 px-0"}%>
    <%= link_to "Add post", new_post_path, {class: "btn btn-primary w-25 m-3 px-0"} %>
  </div>
</div>