config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy]
  end
  
  resources :posts, only: [:new, :create, :destroy, :edit, :update] do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]

  namespace :api, defaults: { format: :json } do
    resources :posts, only: [:index] do
      resources :comments, only: [:create, :index]
    end
  end
end

app/views/_partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible" role="alert">
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
   </div>
<% end %>

app/views/_partials/_header-bulma.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "MyBLOG", root_path, class: 'ps-4 mx-5 is-link display-4' %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item text-dark" %>
      <%= link_to "Documentation", rswag_ui_path, class: "navbar-item text-dark" %>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "button is-primary" %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "button is-light" %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/_partials/_header.html.erb
<div class="d-flex flex-column justify-content-start align-content-start py-2"> 
  <div class="image-container rounded-circle">
    <%=image_tag(image_url(user), alt: "User#{user.id} photo", class: "rounded-circle") %>
  </div>
  <div class="user_container d-flex justify-content-between">
     <h2><%= user.name %></h2>
     <span>Number of posts: <%= post_counter(user) %></span>
  </div>
</div>

app/views/_partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-5 w-100 mb-5">
  <%= link_to "My BLOG", root_path, class: 'navbar-brand ps-4 mx-5' %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-bs-controls="navbarNav" aria-expanded="false" aria-bs-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse me-4" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
          <%= link_to "Home", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About Us</a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in",  new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up",  new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/_partials/_pagy.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").
  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy) -%>
<%#                            -%><nav aria-label="pager" class="d-flex justify-content-center pagy_nav margin-top-05 mb-1 pagination" role="navigation">
<% if pagy.prev                -%>  <button class="pagy-btn margin-right-025"><%== link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous" class="pagy-link"') %></button>
<% else                        -%>  <button class="pagy-btn-disabled margin-right-025"><%== pagy_t('pagy.nav.prev') %></button>
<% end                         -%>
<% pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>  <button class="pagy-page-btn margin-right-025"><%== link.call(item, item,'class="pagy-link"') %></button>
<%   elsif item.is_a?(String)  -%>  <button class="pagy-page-btn-disabled margin-right-025"><%= item %></button>
<%   elsif item == :gap        -%>  <button class="pagy-page-btn-disabled margin-right-025"><%== pagy_t('pagy.nav.gap') %></button>
<%   end                       -%>
<% end                         -%>
<% if pagy.next                -%>  <button class="pagy-btn margin-right-025"><%== link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next" class="pagy-link"') %></button>
<% else                        -%>  <button class="pagy-btn-disabled margin-right-025"><%== pagy_t('pagy.nav.next') %></button>
<% end                         -%>
<%#                            -%></nav>